/* commands-data.js — ВСЕ ТЕКСТЫ и КОМАНДЫ страницы команд.
   T — тексты интерфейса (RU/EN). M — модули и команды.
   Добавить команду: найди нужный модуль в M и добавь объект в его массив c:[...].
   Поля команды: c — название, a:1 — только админам, b — описание,
   o — параметры [имя, {ru,en}, 1 если необязательный], note — примечание. */
const T={
ru:{sub:"Все slash-команды бота. Нажми на команду, чтобы скопировать её, на строку — чтобы увидеть параметры.",search:"Найти команду…",all:"Все",admin:"админам",opt:"необязательно",none:"Параметров нет.",empty:"Ничего не найдено. Попробуй другое слово.",copied:"скопировано",param:"Параметр",desc:"Что указать",
foot:'<a href="https://discord.gg/5FC7pRP5dN">Сервер поддержки</a> · <a href="https://github.com/Privett/Matrix">GitHub</a>'},
en:{sub:"Every slash command of the bot. Click a command to copy it, click the row to see its options.",search:"Search commands…",all:"All",admin:"admins only",opt:"optional",none:"No options.",empty:"Nothing found. Try another word.",copied:"copied",param:"Option",desc:"What to enter",
foot:'<a href="https://discord.gg/5FC7pRP5dN">Support server</a> · <a href="https://github.com/Privett/Matrix">GitHub</a>'}};

const M=[
{id:"giveaway",n:{ru:"Раздачи игр",en:"Game giveaways"},d:{ru:"Бот присылает раздачи в выбранный канал и пингует нужную роль.",en:"The bot posts giveaways to a channel and pings the role you choose."},c:[
 {c:"/addchannel",a:1,b:{ru:"Добавить канал для раздач",en:"Add a giveaway channel"},o:[["role",{ru:"Роль, которую бот будет пинговать",en:"Role the bot will ping"}],["giveaway_delete",{ru:"Удалять сообщение раздачи после завершения (Да / Нет)",en:"Delete the giveaway message when it ends (Yes / No)"}]]}]},
{id:"stalzone",n:{ru:"Stalzone",en:"Stalzone"},d:{ru:"Выбросы, калькуляторы сессий и привязка аккаунта.",en:"Emissions, session calculators and account linking."},c:[
 {c:"/stalzone emission",a:1,b:{ru:"Уведомления о выбросах",en:"Emission notifications"},o:[["added",{ru:"Добавить или удалить канал уведомлений",en:"Add or remove the notification channel"}]]},
 {c:"/stalzone sessionlvlcalc",b:{ru:"Сколько игр до желаемого уровня",en:"How many games to reach a level"},o:[["Средние очки за игру / Average points per game",{ru:"Ваши средние очки за игру (целое число больше 0)",en:"Your average points per game (whole number above 0)"}],["Текущий уровень / Current level",{ru:"Ваш уровень сейчас",en:"Your current level"}],["Желаемый уровень / Desired level",{ru:"Уровень, который хотите получить",en:"The level you want to reach"}]],note:{ru:"Открывается окно с тремя полями. Бот ответит только вам: сколько игр нужно, сколько монет за игру и сколько монет всего.",en:"Opens a window with three fields. The bot replies only to you: games needed, coins per game and total coins."}},
 {c:"/stalzone sessioncoincalc",b:{ru:"Сколько игр до желаемого количества монет",en:"How many games to reach a coin amount"},o:[["Средние очки за игру / Average points per game",{ru:"Ваши средние очки за игру (целое число больше 0)",en:"Your average points per game (whole number above 0)"}],["Желаемые монеты / Desired coins",{ru:"Сколько монет нужно набрать (больше 0)",en:"How many coins you want to earn (above 0)"}]],note:{ru:"Бот ответит только вам: сколько игр нужно, сколько монет за игру и сколько уровней вы получите.",en:"The bot replies only to you: games needed, coins per game and levels gained."}},
 {c:"/connect stalzone",b:{ru:"Привязать аккаунт Stalzone",en:"Link your Stalzone account"},o:[["name",{ru:"Имя персонажа",en:"Character name"}],["region",{ru:"Регион персонажа",en:"Character region"}]],note:{ru:"Перезарядка: 6 минут.",en:"Cooldown: 6 minutes."}}]},
{id:"sens",n:{ru:"Sens Calc",en:"Sens Calc"},d:{ru:"Чувствительность прицеливания (ADS). Два алгоритма: стандартная логика и логика Stalcraft Wiki.",en:"Aim-down-sights sensitivity. Two algorithms: standard logic and Stalcraft Wiki logic."},c:[
 {c:"/senscalc text",b:{ru:"Расчёт по вашим параметрам",en:"Calculate from your values"},o:[["calc_mode",{ru:"Алгоритм расчёта",en:"Calculation algorithm"}],["sens",{ru:"Основная чувствительность мыши, напр. 0.5",en:"Main mouse sensitivity, e.g. 0.5"}],["fov",{ru:"Угол обзора, напр. 90",en:"Field of view, e.g. 90"}],["zooms",{ru:"Название игры (stalcraftx) или уровни зума (1.0 2.4 4.0)",en:"Game name (stalcraftx) or zoom levels (1.0 2.4 4.0)"}]]},
 {c:"/senscalc file",b:{ru:"Обновить ADS прямо в JSON-файле",en:"Update ADS inside your JSON file"},o:[["calc_mode",{ru:"Алгоритм расчёта",en:"Calculation algorithm"}],["file",{ru:"JSON-файл с настройками",en:"JSON file with your settings"}]]}]},
{id:"ascii",n:{ru:"ASCII-арт",en:"ASCII art"},d:{ru:"Превращает картинки в символы.",en:"Turns images into characters."},c:[
 {c:"/image2text",b:{ru:"Изображение в текстовый ASCII-арт",en:"Image to text ASCII art"},o:[["file",{ru:"Изображение",en:"The image"}],["ascii_mode",{ru:"Пресет (standart, modular…) или свои символы",en:"Preset (standart, modular…) or your own characters"}],["resize",{ru:"Размер ШхВ, напр. 100x100",en:"Size as WxH, e.g. 100x100"}]]},
 {c:"/image2image",b:{ru:"Изображение в ASCII-картинку",en:"Image to ASCII picture"},o:[["file",{ru:"Изображение",en:"The image"}],["ascii_mode",{ru:"Пресет или свои символы",en:"Preset or your own characters"}],["thickness",{ru:"Толщина символов, 1–3 (по умолчанию 1)",en:"Character thickness, 1–3 (default 1)"}],["font_scale",{ru:"Размер шрифта, 0.5–2.0 (по умолчанию 1.0)",en:"Font scale, 0.5–2.0 (default 1.0)"}],["target_width_chars",{ru:"Ширина в символах, 50–200 (по умолчанию 120)",en:"Width in characters, 50–200 (default 120)"}],["resize",{ru:"Размер ШхВ, напр. 100x100",en:"Size as WxH, e.g. 100x100"}]]}]},
{id:"protect",n:{ru:"Защита",en:"Protection"},d:{ru:"Ловушка для ботов-спамеров.",en:"A trap for spam bots."},c:[
 {c:"/antibot",a:1,b:{ru:"Канал-ловушка для спам-ботов",en:"Trap channel for spam bots"},o:[["Канал / Channel",{ru:"Текстовый или голосовой канал-ловушка",en:"Text or voice trap channel"}],["Действие / Action",{ru:"Softban (кик), Ban или Disabled",en:"Softban (kick), Ban or Disabled"}],["Экспериментальные / Experimental",{ru:"Reinvite, Random Channel Name, Random Channel Name (Chaos). Необязательно",en:"Reinvite, Random Channel Name, Random Channel Name (Chaos). Optional"}]],note:{ru:"Если канала ещё нет, бот сам создаст канал antibot с предупреждением и режимом Softban. Любое сообщение в этом канале наказывается. Кнопка «Kicks» показывает статистику сервера и всех серверов.",en:"If no trap channel exists, the bot creates an antibot channel with a warning and Softban mode. Any message sent there is punished. The Kicks button shows server and global stats."}}]},
{id:"other",n:{ru:"Прочее",en:"Other"},d:{ru:"",en:""},c:[
 {c:"/help",b:{ru:"Список команд или подробности по одной",en:"Command list or details on one"},o:[["command",{ru:"Название команды, напр. help. Пусто — общий список",en:"Command name, e.g. help. Leave empty for the list"},1]]},
 {c:"/send_owner",b:{ru:"Отправить идею или баг разработчику",en:"Send an idea or bug to the developer"},o:[["message",{ru:"Текст сообщения",en:"Message text"}],["screenshot",{ru:"Скриншот (изображение или файл)",en:"Screenshot (image or file)"},1]]}]}
];

